apiVersion: v1
kind: Service
metadata:
  name:  payoutplanservice-svc
  labels:
    app: payoutplanservice
spec:
  selector:
    app:  payoutplanservice
  type: NodePort
  ports:
   - port:  3002
     nodePort: 30005
     protocol: TCP